[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ✅ UPDATED: Better API redirects with CORS headers
[[redirects]]
  from = "/api/electricitymap/*"
  to = "https://api.electricitymap.org/v3/:splat"
  status = 200
  force = false
  headers = {X-Requested-With = "XMLHttpRequest"}

[[redirects]]
  from = "/api/entsoe/*"
  to = "https://web-api.tp.entsoe.eu/api/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/api/rebase/*"
  to = "https://api.rebase.energy/:splat"
  status = 200
  force = false

# ✅ Add CORS headers for API calls
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, auth-token"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"