[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# SPA routing - redirect all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API redirects for production (optional - your app uses mock data fallbacks)
[[redirects]]
  from = "/api/rebase/*"
  to = "https://api.rebase.energy/:splat"
  status = 200
  force = false
  
[[redirects]]
  from = "/api/entsoe/*"
  to = "https://web-api.tp.entsoe.eu/api/:splat" 
  status = 200
  force = false

[[redirects]]
  from = "/api/electricitymap/*"
  to = "https://api.electricitymap.org/v3/:splat"
  status = 200
  force = false

# Headers for better performance
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"